### ISSUE TITLE
This doesn't run on Lonux

### ISSUE THREAD

**Issue by AtomJon** [LasseVKP/LDCBots#1]
Hello there, I downloaded this application and tried to run it on my custom built Gentoo + OpenRC + XFCE, but it says: "No environment variable fou..."
Obviously that's because this is made in bad programming language and should be coded in Rust instead

**Comment by LasseVKP** [comment]
That's because you need to have a file called ".env" in the same directory.
Inside the ".env" file you need to write:
```
DATABASE_URL = "<MongoDB database URL>"
DATABASE_NAME = "<Database name>"

ECONOMY_TOKEN = "<Discord bot token>"
```

And of course change the values to the values you have
